# Run unit tests on any branch/fork pull request
on:
  - pull_request
  - push

name: Unit tests

jobs:
  unit:
    name: unit tests - stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stack: ["2.7.5"]
        ghc: ["9.0.2"]
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-stack
    - run: env
    # There is a bug related to the compilation order of Stack which causes a failure when compiling old-time and network together with
    # all other packages, see: https://github.com/tek/incipit/issues/1 and https://github.com/commercialhaskell/stack/issues/5414
    - run: stack build old-time
    - run: stack build network
    - run: stack build
    - run: make test-unit
    # diable e2e tests for now, it seems that the ports opened by there server thread are
    # accessible in github actions. We could try to run them in a container.
    #- run: make test-e2e
  test-e2e:
    needs: unit
    name: unit tests - stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    container:
      image: haskell:9.0.2-buster
    strategy:
      matrix:
        stack: ["2.7.5"]
        ghc: ["9.0.2"]
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-stack
    - name: Permissions bug workaround
      run: "chown -R $(id -un):$(id -gn) ~"
    - run: stack --allow-different-user build old-time
    - run: stack --allow-different-user build network
    - run: stack --allow-different-user build
    - name: 'Create env file'
      run: |
        touch .env
        echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
        echo TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} >> .env
        echo TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }} >> .env
        cat .env
    - run: stack --allow-different-user test --ghc-options "-O0 -j4 +RTS -A128m -n2m -RTS" wow-stream:wow-stream-test-e2e
